rm -f ./Data/Geometry/dwal1.log
rm -f ./Data/Geometry/dwall1.log
rm -f ./Data/Geometry/dwall1.vtk
rm -f ./Data/Geometry/dwall360.log
rm -f ./Data/Geometry/dwallr360.log
rm -f ./Data/Geometry/dwallr360.vtk
rm -f ./Data/Geometry/jdiv00.log
rm -f ./Data/Geometry/jdiv01.log
rm -f ./Data/Geometry/jdiv11.log
rm -f ./Data/Geometry/jdiv11.vtk
rm -f ./Data/Geometry/jdiv41.log
rm -f ./Data/Geometry/jdiv41.vtk
rm -f ./Data/Geometry/jwal1.log
rm -f ./Data/Geometry/jwall1.log
rm -f ./Data/Geometry/jwall1.vtk
rm -f ./Data/Geometry/jwall360.log
rm -f ./Data/Geometry/jwallr360.log
rm -f ./Data/Geometry/jwallr360.vtk
rm -f ./Data/Geometry/vtkcomb.log
rm -f ./Data/Geometry/vtkcomb.vtk
rm -f ./DEMO-double-null/G/beq+wall.ps
rm -f ./DEMO-double-null/G/dR.ps
rm -f ./DEMO-double-null/G/dZ.ps
rm -f ./DEMO-double-null/G/powd.ctl
rm -f ./DEMO-double-null/G/powd_geofldx.vtk
rm -f ./DEMO-double-null/G/powd_geoqm.vtk
rm -f ./DEMO-double-null/G/powd_geoq.out
rm -f ./DEMO-double-null/G/powd_gnu_cart.gnu
rm -f ./DEMO-double-null/G/powd_gnu_dR.gnu
rm -f ./DEMO-double-null/G/powd_gnu_dZ.gnu
rm -f ./DEMO-double-null/G/powd_gnu.gnu
rm -f ./DEMO-double-null/G/powd_gnusil.gnu
rm -f ./DEMO-double-null/G/powd.log
rm -f ./DEMO-double-null/G/table.dat
rm -f ./DEMO-double-null/G/tabledR.dat
rm -f ./DEMO-double-null/G/tabledZ.dat
rm -f ./DEMO-double-null/G_upside_down/beq+wall.ps
rm -f ./DEMO-double-null/G_upside_down/dR.ps
rm -f ./DEMO-double-null/G_upside_down/dZ.ps
rm -f ./DEMO-double-null/G_upside_down/powd.ctl
rm -f ./DEMO-double-null/G_upside_down/powd_geofldx.vtk
rm -f ./DEMO-double-null/G_upside_down/powd_geoqm.vtk
rm -f ./DEMO-double-null/G_upside_down/powd_geoq.out
rm -f ./DEMO-double-null/G_upside_down/powd_gnu_cart.gnu
rm -f ./DEMO-double-null/G_upside_down/powd_gnu_dR.gnu
rm -f ./DEMO-double-null/G_upside_down/powd_gnu_dZ.gnu
rm -f ./DEMO-double-null/G_upside_down/powd_gnu.gnu
rm -f ./DEMO-double-null/G_upside_down/powd_gnusil.gnu
rm -f ./DEMO-double-null/G_upside_down/powd.log
rm -f ./DEMO-double-null/G_upside_down/table.dat
rm -f ./DEMO-double-null/G_upside_down/tabledR.dat
rm -f ./DEMO-double-null/G_upside_down/tabledZ.dat
rm -f ./DEMO-double-null/H/dwallr360_geobjq.vtk
rm -f ./DEMO-double-null/H/dwallr360_geoptq.vtk
rm -f ./DEMO-double-null/H/dwallr360_hdsgen.out
rm -f ./DEMO-double-null/H/dwallr360_hds.hds
rm -f ./DEMO-double-null/H/dwallr360_hdsm.vtk
rm -f ./DEMO-double-null/H/dwallr360_hdsq.vtk
rm -f ./DEMO-double-null/H/dwallr360.log
rm -f ./DEMO-double-null/H_upside_down/dwallr360_geobjq.vtk
rm -f ./DEMO-double-null/H_upside_down/dwallr360_geoptq.vtk
rm -f ./DEMO-double-null/H_upside_down/dwallr360_hdsgen.out
rm -f ./DEMO-double-null/H_upside_down/dwallr360_hds.hds
rm -f ./DEMO-double-null/H_upside_down/dwallr360_hdsm.vtk
rm -f ./DEMO-double-null/H_upside_down/dwallr360_hdsq.vtk
rm -f ./DEMO-double-null/H_upside_down/dwallr360.log
rm -r ./DEMO-double-null/ismtemp*
rm -f ./DEMO-double-null/P/eich.log
rm -f ./DEMO-double-null/P/eich_powcal.out
rm -f ./DEMO-double-null/P/exp-double.log
rm -f ./DEMO-double-null/P/exp-double_powcal.out
rm -f ./DEMO-double-null/P/exp.log
rm -f ./DEMO-double-null/P/exp_powcal.out
rm -f ./DEMO-double-null/P_upside_down/eich.log
rm -f ./DEMO-double-null/P_upside_down/eich_powcal.out
rm -f ./DEMO-double-null/P_upside_down/exp-double.log
rm -f ./DEMO-double-null/P_upside_down/exp-double_powcal.out
rm -f ./DEMO-double-null/P_upside_down/exp-inboard.log
rm -f ./DEMO-double-null/P_upside_down/exp-inboard_powcal.out
rm -f ./DEMO-double-null/P_upside_down/exp.log
rm -f ./DEMO-double-null/P_upside_down/exp-outboard.log
rm -f ./DEMO-double-null/P_upside_down/exp-outboard_powcal.out
rm -f ./DEMO-double-null/P_upside_down/exp_powcal.out
rm -f ./DEMO-double-null/S/dwallr360.ctl
rm -f ./DEMO-double-null/S/dwallr360_geofldx.vtk
rm -f ./DEMO-double-null/S/dwallr360_geoqm.vtk
rm -f ./DEMO-double-null/S/dwallr360_geoq.out
rm -f ./DEMO-double-null/S/dwallr360_gnu_cart.gnu
rm -f ./DEMO-double-null/S/dwallr360_gnu_dR.gnu
rm -f ./DEMO-double-null/S/dwallr360_gnu_dZ.gnu
rm -f ./DEMO-double-null/S/dwallr360_gnu.gnu
rm -f ./DEMO-double-null/S/dwallr360_gnusil.gnu
rm -f ./DEMO-double-null/S/dwallr360.log
rm -f ./DEMO-double-null/S_upside_down/dwallr360.ctl
rm -f ./DEMO-double-null/S_upside_down/dwallr360_geofldx.vtk
rm -f ./DEMO-double-null/S_upside_down/dwallr360_geoqm.vtk
rm -f ./DEMO-double-null/S_upside_down/dwallr360_geoq.out
rm -f ./DEMO-double-null/S_upside_down/dwallr360_gnu_cart.gnu
rm -f ./DEMO-double-null/S_upside_down/dwallr360_gnu_dR.gnu
rm -f ./DEMO-double-null/S_upside_down/dwallr360_gnu_dZ.gnu
rm -f ./DEMO-double-null/S_upside_down/dwallr360_gnu.gnu
rm -f ./DEMO-double-null/S_upside_down/dwallr360_gnusil.gnu
rm -f ./DEMO-double-null/S_upside_down/dwallr360.log
rm -f ./ITER-valid/G/top1barpart.ctl
rm -f ./ITER-valid/G/top1barpart_geoqm.vtk
rm -f ./ITER-valid/G/top1barpart_geoq.out
rm -f ./ITER-valid/G/top1barpart.log
rm -f ./ITER-valid/H/hdshad_geobjq.vtk
rm -f ./ITER-valid/H/hdshad_geoptq.vtk
rm -f ./ITER-valid/H/hdshad_hdsgen.out
rm -f ./ITER-valid/H/hdshad_hds.hds
rm -f ./ITER-valid/H/hdshad_hdsm.vtk
rm -f ./ITER-valid/H/hdshad_hdsq.vtk
rm -f ./ITER-valid/H/hdshad.log
rm -r ./ITER-valid/ismtemp*
rm -f ./ITER-valid/P/itertest1_gnu_radn.gnu
rm -f ./ITER-valid/P/itertest1.log
rm -f ./ITER-valid/P/itertest1_powcal.out
rm -f ./ITER-valid/S/gshad.ctl
rm -f ./ITER-valid/S/gshad_geofldx.vtk
rm -f ./ITER-valid/S/gshad_geoqm.vtk
rm -f ./ITER-valid/S/gshad_geoq.out
rm -f ./ITER-valid/S/gshad_gnu_cart.gnu
rm -f ./ITER-valid/S/gshad_gnu_dR.gnu
rm -f ./ITER-valid/S/gshad_gnu_dZ.gnu
rm -f ./ITER-valid/S/gshad_gnu.gnu
rm -f ./ITER-valid/S/gshad_gnusil.gnu
rm -f ./ITER-valid/S/gshad.log
rm -f ./JET-ant/elt1.txt
rm -f ./JET-ant/elt22.txt
rm -f ./JET-ant/jant_antest.out
rm -f ./JET-ant/jant_gnu_cart.gnu
rm -f ./JET-ant/jant_gnu_dR.gnu
rm -f ./JET-ant/jant_gnu_dZ.gnu
rm -f ./JET-ant/jant_gnu.gnu
rm -f ./JET-ant/jant_gnu_radn.gnu
rm -f ./JET-ant/jant_gnu_test.gnu
rm -f ./JET-ant/jant.log
rm -f ./JET-ant/jant.out
rm -f ./JET-ant/jet297.eqdsk
rm -f ./JET-ant/jwall.txt
rm -f ./JET-ant/kprad_00224_6.txt
rm -f ./JET-ant/beq+rays.ps
rm -f ./JET-radn/G/jone.ctl
rm -f ./JET-radn/G/jone_geoqm.vtk
rm -f ./JET-radn/G/jone_geoq.out
rm -f ./JET-radn/G/jone_gnu_cart.gnu
rm -f ./JET-radn/G/jone_gnu_dR.gnu
rm -f ./JET-radn/G/jone_gnu_dZ.gnu
rm -f ./JET-radn/G/jone_gnu.gnu
rm -f ./JET-radn/G/jone_gnusil.gnu
rm -f ./JET-radn/G/jone.log
rm -f ./JET-radn/H/jwallr360_hdsgen.out
rm -f ./JET-radn/H/jwallr360_hds.hds
rm -f ./JET-radn/H/jwallr360.log
rm -r ./JET-radn/ismtemp*
rm -f ./JET-radn/P/jone_anal_gnu_radn.gnu
rm -f ./JET-radn/P/jone_anal.log
rm -f ./JET-radn/P/jone_anal_powcal.out
rm -f ./JET-radn/P/jone_file_gnu_radn.gnu
rm -f ./JET-radn/P/jone_file.log
rm -f ./JET-radn/P/jone_file_powcal.out
rm -f ./JET-radn/P/jone_gnu_radn.gnu
rm -f ./JET-radn/P/jone.log
rm -f ./JET-radn/P/jone_powcal.out
rm -f ./JET-radn/P/tableradn.dat
rm -f ./JET-radn/S/jwallr360.ctl
rm -f ./JET-radn/S/jwallr360_geoqm.vtk
rm -f ./JET-radn/S/jwallr360_geoq.out
rm -f ./JET-radn/S/jwallr360_gnu_cart.gnu
rm -f ./JET-radn/S/jwallr360_gnu_dR.gnu
rm -f ./JET-radn/S/jwallr360_gnu_dZ.gnu
rm -f ./JET-radn/S/jwallr360_gnu.gnu
rm -f ./JET-radn/S/jwallr360_gnusil.gnu
rm -f ./JET-radn/S/jwallr360.log
rm -rf ./ITER-valid_MPI
rm -rf ./JET-radn_MPI
