!>\mainpage SMARDDA-PFC Further Tests
!! 
!! 
!! \section sec1 What this repo contains
!! 
!! Primarily the test cases \n
!! - DEMO-double-null  
!! - ITER-valid  
!! - JET-ant  
!! - JET-radn  
!! 
!! which are described separately and in more detail in \ref sec3
!! 
!! Each test case corresponds to a subdirectory of the repo, wherein it
!! is run by invoking the local case.bash script, with output appearing
!! subdirectories G, S, H and P corresponding to the principal steps
!! of the SMARDDA-PFC workflow, where main interest attaches to P which will
!! be populated with details of power deposition on PFCs.  Apart from the
!! script and .ctl files, the geometry and magnetic field information
!! needed to define each set of calculations sits in subdirectory Data,
!! which in turn has subdirectories
!! 
!! \arg Equilibrium : .eqdsk files defining magnetic field
!! \arg Geometry : Files used to define geometry, including
!!    - .bash scripts to generate geometry by rotation/translation of  
!!    - .dat files defining first wall silhouettes as a set of points  
!!    - .txt files similarly, but for plotting  
!!    - .ctl files defining rotation and units conversion   
!!    - .py files used in the definition of geometry  
!!    - .log files (after executing cases)
!!    - .vtk files (after executing cases)
!! \arg Misc : Files not fitting into the other categories, e.g.
!!    - *gnu files for 2-D plotting with gnuplot
!!    - .gnup files for direct input to gnuplot
!!    - .txt files describing radiation fields
!! \arg Physics-Radiation : ADAS data files defining radiation
!! \arg VTK : The .vtk files used in calculation, other than those
!!  generated in the Geometry subdirectory
!!
!! with more details about the contents and function of each file to be
!! found in \ref sec2
!>
!! 
!!
!! \section sec2 Description of Data and Script Files
!!
!! \subsection sec2equil Equilibrium
!!	
!! \subsection sec2geom Geometry
!! 
!! \subsection sec2misc Misc
!!
!! \subsection sec2pr Physics-Radiation
!!
!! \subsection sec2VTK VTK
!!
!!
!! \section sec3 Test-Deck
!! 
!! \subsection sec3intro Introduction
!! 
!! This additional set of test cases is designed to demonstrate correct functioning
!! of features added to SMARDDA-PFC in 2020-2026. Data and control files for this
!! extension to the test-deck is in the smiteraux-plus directory, from which
!! the listed set of test cases should be invoked using
!! ./tests.bash
!! which should take less than 15 minutes on a high-end laptop or desktop,
!! but beware that the output files may occupy of order 10 Gbyte. 
!! When no longer needed, the test-deck outputs can be removed using
!! ./tests_clean.bash
!!
!! Note that this collection of tests is much more self-contained compared
!! to the original smiteraux repo, but does rely on the presence of the
!! SMARDDA-PFC executables on the path (i.e. in directories listed by the 
!! environment variable PATH). Otherwise, the case.bash script defined for
!! each test case includes functionality previously found in .sgo files
!! and for example the skeleton .ctl files are now located in the test
!! case directories
!!
!! \subsection sec3cases Cases
!! A brief description of each case follows so that the
!! user may determine which is closest to the problem of current
!! interest and therefore might be most easily modified to solve it. 
!! Each case title begins with name of the device modelled. 
!! Each may also be described by a long name with components separated
!! by dashes, where components of the names in order are
!! an identifier of the equilibrium, the shadowing geometry and
!! the results geometry respectively. 
!! Thus the geometries may be easily identified among the .vtk files
!! in the Data/Geometry and Data/VTK subdirectories and visualised using
!! ParaView,  noting that most of the .vtk files have to be generated by .bash
!! scripts from the .dat files in subdirectory Data/Geometry.
!!
!!
!! \subsubsection sec3P1 DEMO-double-null 
!! Plus-nf6m_CQ2(_upside_down)-dwallr360-dwall1 
!!
!! DEMO case for particle power deposition in double null set-up
!! used to check powcalr duplicates powcal execution.
!! This test case makes use of powcalr. 
!! 360deg poloidal wall defined by consecutive points (first=last) is used to
!! generate .vtk file consisting of a single 1deg toroidal line of quads,
!! and a 360deg toroidal triangulated shadow
!! It also demonstrates that the inboard and outboard \f$\lambda_q\f$, profile_formula
!! and diffusion length can be changed separately.
!!
!! Magnetic equilibrium in planned orientation \n
!! \image html P1.png
!! \image latex P1.eps "Power deposition on dwall1 geometry" width=10cm
!!
!! Magnetic equilibrium inverted, i.e. reflected in horizontal midplane,
!! purely for testing purposes, viewpoint also inverted \n
!! \image html P1ud2.png
!! \image latex P1ud2.eps "Power deposition on dwall1 geometry" width=10cm
!!
!! Provenance\n
!! Case CQ2 (file Dyn_sim_SN_k95_1d65_delta95_0d33_MD_no_p_2NKLP2_v1_0_t_0d434_CQ1.eqdsk)
!! described in  https://idm.euro-fusion.org/?uid=2NX6LP
!!
!! \subsubsection sec3P2 ITER-valid
!! Plus-EQX40-vtkcomb-top1barpart
!! \image html P2gv.png 
!! \image latex P2gv.eps "Illustration of antenna situation within torus" width=10cm
!! \image html P2.png
!! \image latex P2.eps "Power deposition on top1barpart geometry" width=10cm
!! Radiation case to compare with ITER results in Brank et al https://doi.org/10.1016/j.nme.2021.101021
!! Note this uses 21x21 represntation of antenna instead of 61 x 61 as in 
!! Waqar Butt's Masters Report "SMARDDA-PFC and the Powcalr code"
!!
!! Provenance\n
!! Equilibrium EQ40 (file Equil_7d5_outboard_30Nov2011.eqdsk) described in the
!! document AFWS_Final_Report_I2-dB.doc to ITER. \n
!! Geometry files for comparison provided by Matic Brank in email of 2022/07/27,
!! N.B. m instead of mm in CAD
!!
!! \subsubsection sec3P3 JET-ant
!! Plus-jet297-XXX-jdiv11
!! \image html P3.png
!! \image latex P3.eps "Ray paths from divertor tip within LCFS" width=10cm
!! Test of antest code which produces plot of rays "from" element(s) of antenna file.
!! creating jdiv11.vtk as a byproduct. Note that this test does not know
!! device geometry, hence the apparently bent rays due to projection onto \f$(R,Z)\f$
!! of trajectories probably passing through the central space of the tokamak.
!! It could use a ParaView script to produce a 11x11 representation of antenna,
!! but a stored .vtk is used, since the script fails to complete with
!! pvbatch v. 5.10.1 (as used by Ubuntu 22), although other versions do work.
!!
!! \subsubsection sec3P4 JET-radn
!! Plus-jet297-jwallr360-jwall1
!! \image html P4.png
!! \image latex P4.eps "Power deposition on jwall1 geometry" width=10cm
!! JET axisymmetric model - 1deg target in 360deg shadow is used
!! to check conservation of radiated power, using
!! files to test out radiation patterns in \f$(R,Z)\f$ which are
!! 1. circular
!! 2. analytic in magnetic flux
!! 3. specified by input file
!!
!! Provenance\n
!! - g_p89297_t45_011.eqdsk -> jet297.eqdsk (supplied by Gabor Szepesi 16/8/17)
!! - jwall.txt supplied as 003 by Oliver Bardsley 21/5/21
!! (to jetwall_RZ.dat in ../Data/Geometry , removing first line, copying 2nd to end)
!! - kprad_00224_6.txt supplied as kprad_rad_00224_6 by Oliver Bardsley 21/5/21
!!
